# Generated by Django 4.1 on 2022-11-26 21:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, max_length=72)),
                ('main_image', models.ImageField(upload_to='notices/images/')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('notice_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informatica.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeCarousel/images/')),
                ('title', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=72)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informatica.notice')),
            ],
        ),
    ]
